main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: /#papers
    weight: 20
  - name: Experience
    url: experience/
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
